name: BlazorToGHPage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-blazor-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish HelloTemplateBlazor.Wasm/HelloTemplateBlazor.Wasm.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-page
          target-folder: dist/Web/wwwroot
